insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Outlander Sport', 'Mauv', null, 395);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'xB', 'Blue', null, 378);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'GTO', 'Blue', null, 253);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'IS F', 'Crimson', null, 278);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'T100 Xtra', 'Khaki', null, 230);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'RAV4', 'Orange', null, 201);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'QX', 'Orange', null, 327);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Mazda6', 'Turquoise', null, 279);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'TL', 'Teal', null, 309);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'G-Series G20', 'Puce', null, 312);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Matrix', 'Yellow', null, 227);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'L300', 'Teal', null, 318);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'MDX', 'Orange', null, 334);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Brat', 'Mauv', null, 248);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'E-Class', 'Khaki', null, 205);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Savana 3500', 'Yellow', null, 328);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Civic', 'Blue', null, 311);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Tundra', 'Teal', null, 374);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Silverado 1500', 'Teal', null, 331);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Crown Victoria', 'Indigo', null, 274);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Escort', 'Maroon', null, 312);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Montero Sport', 'Yellow', null, 299);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'CX-5', 'Indigo', null, 234);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Express 2500', 'Crimson', null, 342);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '626', 'Pink', null, 358);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Envoy XL', 'Goldenrod', null, 221);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Lancer', 'Teal', null, 228);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'F-Series', 'Puce', null, 274);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sierra 3500', 'Crimson', null, 265);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'MKS', 'Red', null, 209);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'S2000', 'Purple', null, 204);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Caprice Classic', 'Yellow', null, 265);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Excursion', 'Crimson', null, 326);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'M3', 'Goldenrod', null, 364);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Breeze', 'Turquoise', null, 281);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'LR2', 'Pink', null, 363);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'LX', 'Puce', null, 218);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Focus ST', 'Crimson', null, 203);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Eos', 'Green', null, 357);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Envoy XL', 'Crimson', null, 302);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Skylark', 'Mauv', null, 385);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Rio', 'Maroon', null, 315);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Fit', 'Blue', null, 270);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Malibu', 'Crimson', null, 346);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Lucerne', 'Pink', null, 339);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'LS', 'Maroon', null, 280);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'SJ', 'Turquoise', null, 239);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sportvan G20', 'Orange', null, 322);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Golf', 'Maroon', null, 253);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Trooper', 'Maroon', null, 219);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'XL-7', 'Maroon', null, 329);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '600', 'Indigo', null, 311);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Rabbit', 'Aquamarine', null, 254);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Endeavor', 'Green', null, 209);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Gemini', 'Violet', null, 287);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'LaCrosse', 'Purple', null, 305);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Golf III', 'Green', null, 355);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Silverado 1500', 'Turquoise', null, 306);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Oasis', 'Mauv', null, 309);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Avalanche 1500', 'Indigo', null, 367);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Terrain', 'Khaki', null, 283);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'NSX', 'Pink', null, 259);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Terrain', 'Indigo', null, 269);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Grand Prix', 'Goldenrod', null, 212);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'LaCrosse', 'Turquoise', null, 306);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'GX', 'Puce', null, 227);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'XJ Series', 'Blue', null, 213);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Electra', 'Maroon', null, 397);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'A6', 'Orange', null, 392);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Prelude', 'Purple', null, 209);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Envoy', 'Fuscia', null, 366);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Daewoo Lacetti', 'Indigo', null, 225);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Grand Prix', 'Violet', null, 291);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Colt Vista', 'Mauv', null, 309);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'A3', 'Green', null, 310);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Tahoe', 'Teal', null, 376);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '1 Series', 'Green', null, 208);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Grand Cherokee', 'Blue', null, 221);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'LS', 'Maroon', null, 277);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Xterra', 'Violet', null, 241);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'GS', 'Teal', null, 213);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'F430', 'Goldenrod', null, 293);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sonoma', 'Purple', null, 283);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'CR-V', 'Green', null, 275);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'XC70', 'Purple', null, 246);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'QX', 'Goldenrod', null, 398);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'B-Series Plus', 'Maroon', null, 324);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'GTI', 'Khaki', null, 319);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'XC70', 'Goldenrod', null, 298);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Avalanche 2500', 'Fuscia', null, 319);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'SJ', 'Turquoise', null, 300);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'SC', 'Khaki', null, 320);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Ram 1500 Club', 'Puce', null, 327);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Bronco', 'Mauv', null, 388);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Cavalier', 'Mauv', null, 373);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Eclipse', 'Puce', null, 395);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Cabriolet', 'Red', null, 336);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Range Rover', 'Maroon', null, 264);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Accent', 'Violet', null, 268);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Envoy', 'Red', null, 284);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Corvette', 'Pink', null, 227);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Viper', 'Purple', null, 341);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Shadow', 'Orange', null, 292);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '2500 Club Coupe', 'Crimson', null, 384);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Outback', 'Maroon', null, 319);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Outback', 'Purple', null, 215);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Seville', 'Green', null, 363);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'F-Series', 'Aquamarine', null, 261);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Aztek', 'Crimson', null, 386);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Lanos', 'Crimson', null, 267);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Accent', 'Purple', null, 381);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Leaf', 'Fuscia', null, 222);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'SC', 'Mauv', null, 391);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '9-3', 'Goldenrod', null, 232);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Monaro', 'Maroon', null, 292);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Justy', 'Green', null, 301);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Altima', 'Puce', null, 287);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'GranTurismo', 'Aquamarine', null, 329);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Discovery', 'Maroon', null, 375);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Ram Van 2500', 'Teal', null, 260);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Jetta', 'Mauv', null, 231);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Boxster', 'Teal', null, 359);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'SLS-Class', 'Puce', null, 326);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Prius', 'Violet', null, 212);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Suburban 2500', 'Goldenrod', null, 345);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'C70', 'Pink', null, 318);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'TT', 'Puce', null, 308);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Explorer', 'Puce', null, 213);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'SVX', 'Maroon', null, 354);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Fusion', 'Mauv', null, 212);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'LX', 'Puce', null, 330);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Viper', 'Mauv', null, 249);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Safari', 'Purple', null, 341);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'GX', 'Indigo', null, 251);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sierra 2500', 'Khaki', null, 336);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '90', 'Maroon', null, 390);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'EXP', 'Aquamarine', null, 288);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'XJ Series', 'Purple', null, 398);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Firebird', 'Crimson', null, 236);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Grand Voyager', 'Yellow', null, 354);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'IS', 'Turquoise', null, 227);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Tempo', 'Green', null, 254);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Mirage', 'Aquamarine', null, 309);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Concorde', 'Violet', null, 255);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Galant', 'Violet', null, 313);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Outlook', 'Mauv', null, 235);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'JUKE', 'Crimson', null, 320);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'S6', 'Pink', null, 230);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Mariner', 'Purple', null, 346);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'C30', 'Puce', null, 235);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Cabriolet', 'Pink', null, 353);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Patriot', 'Puce', null, 341);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Ram 2500', 'Fuscia', null, 277);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Impulse', 'Orange', null, 295);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Intrepid', 'Orange', null, 261);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Grand Am', 'Indigo', null, 349);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Miata MX-5', 'Goldenrod', null, 343);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Laser', 'Pink', null, 205);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Caravan', 'Teal', null, 236);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Express 3500', 'Green', null, 331);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '200', 'Green', null, 311);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Thunderbird', 'Turquoise', null, 314);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Forester', 'Puce', null, 250);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '2e', 'Red', null, 241);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Escort', 'Aquamarine', null, 339);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Forester', 'Turquoise', null, 257);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Canyon', 'Turquoise', null, 231);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'G-Series 2500', 'Violet', null, 259);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sorento', 'Aquamarine', null, 259);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Hombre Space', 'Crimson', null, 295);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'LS Hybrid', 'Violet', null, 302);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Touareg', 'Aquamarine', null, 318);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Optima', 'Khaki', null, 204);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Bonneville', 'Indigo', null, 359);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Tahoe', 'Khaki', null, 223);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Bronco', 'Turquoise', null, 238);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'A4', 'Maroon', null, 358);
insert into shape (dtype, name, color, size, complex_id) values ('complex', '1500', 'Goldenrod', null, 306);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Pilot', 'Khaki', null, 356);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Intrigue', 'Blue', null, 265);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Esprit', 'Yellow', null, 298);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Astro', 'Indigo', null, 209);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Yukon XL 1500', 'Fuscia', null, 277);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sportage', 'Turquoise', null, 303);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Rodeo', 'Fuscia', null, 201);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sonata', 'Indigo', null, 353);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Volare', 'Orange', null, 252);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Avalon', 'Pink', null, 323);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'T100 Xtra', 'Turquoise', null, 345);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Xterra', 'Puce', null, 280);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'SM', 'Pink', null, 349);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sierra 2500', 'Aquamarine', null, 341);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'TT', 'Orange', null, 329);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Club Wagon', 'Yellow', null, 323);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Jetta', 'Red', null, 323);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Savana 2500', 'Orange', null, 397);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Sephia', 'Violet', null, 375);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'CLS-Class', 'Mauv', null, 298);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Civic', 'Teal', null, 375);
insert into shape (dtype, name, color, size, complex_id) values ('complex', 'Venture', 'Indigo', null, 380);
