insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 1, 'Avenger', null, 38, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 2, 'Town & Country', null, 50, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 3, 'Savana 1500', null, 62, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 4, 'Silverado', null, 42, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 5, 'Cherokee', null, 12, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 6, 'Grand Prix', null, 3, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 7, 'Savana 1500', null, 69, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 8, 'Town Car', null, 49, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 9, 'Grand Prix', null, 63, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 10, 'Exige', null, 55, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 11, 'Forenza', null, 50, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 12, 'SRX', null, 20, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 13, '6 Series', null, 53, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 14, 'Elan', null, 37, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 15, 'B-Series Plus', null, 21, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 16, 'Elan', null, 8, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 17, 'Silverado 3500HD', null, 61, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 18, 'Vantage', null, 20, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 19, 'M6', null, 58, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 20, 'Quattro', null, 39, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 21, '6 Series', null, 33, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 22, 'Tribute', null, 10, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 23, 'Exige', null, 35, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 24, 'Corolla', null, 11, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 25, 'Yukon XL 1500', null, 26, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 26, 'CLK-Class', null, 64, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 27, 'LSS', null, 25, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 28, '350Z Roadster', null, 55, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 29, 'CTS', null, 34, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 30, '3500 Club Coupe', null, 65, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 31, 'Prius', null, 59, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 32, 'LR3', null, 25, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 33, 'V90', null, 35, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 34, 'Range Rover', null, 62, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 35, 'Matrix', null, 68, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 36, 'DeVille', null, 5, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 37, 'Insight', null, 11, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 38, 'Impala', null, 26, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 39, 'C30', null, 27, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 40, 'Celica', null, 58, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 41, 'Century', null, 2, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 42, 'Outback', null, 61, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 43, 'Gran Sport', null, 35, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 44, 'Protege5', null, 22, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 45, 'Express 2500', null, 19, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 46, 'NSX', null, 61, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 47, 'Mountaineer', null, 11, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 48, 'Starion', null, 43, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 49, 'Sonata', null, 47, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 50, 'Taurus', null, 72, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 51, 'SC', null, 63, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 52, 'Prius Plug-in Hybrid', null, 18, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 53, 'Hombre', null, 57, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 54, 'Truck', null, 13, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 55, 'Continental', null, 34, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 56, 'F-Series', null, 68, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 57, 'Corvette', null, 46, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 58, 'Riviera', null, 61, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 59, 'A6', null, 62, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 60, 'Titan', null, 42, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 61, '9000', null, 26, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 62, 'Civic', null, 61, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 63, 'X3', null, 24, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 64, 'Passat', null, 53, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 65, 'ES', null, 13, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 66, 'Caprice Classic', null, 39, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 67, 'Tundra', null, 1, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 68, 'Tribute', null, 54, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 69, '57', null, 1, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 70, 'Crossfire', null, 36, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 71, '3000GT', null, 2, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 72, 'Galant', null, 65, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 73, 'GS', null, 15, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 74, 'Hombre', null, 17, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 75, 'Mighty Max Macro', null, 39, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 76, 'Yukon Denali', null, 33, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 77, 'Savana', null, 3, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 78, 'Park Avenue', null, 54, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 79, 'Dakota Club', null, 44, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 80, 'Golf', null, 34, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 81, 'Continental', null, 29, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 82, 'Express 2500', null, 29, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 83, 'Highlander', null, 66, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 84, 'Impreza', null, 12, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 85, 'M5', null, 64, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 86, 'Navigator L', null, 13, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 87, 'Park Avenue', null, 48, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 88, 'Amigo', null, 27, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 89, 'GS', null, 59, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 90, 'Envoy XL', null, 5, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 91, 'Grand Cherokee', null, 48, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 92, 'Neon', null, 44, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 93, 'V70', null, 43, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 94, 'Verano', null, 45, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 95, 'Touareg', null, 16, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 96, 'V50', null, 47, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 97, '9-3', null, 53, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 98, '3 Series', null, 13, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 99, 'Contour', null, 65, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 100, 'Corolla', null, 44, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 101, 'Continental Flying Spur', null, 69, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 102, 'MX-5', null, 57, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 103, 'Riviera', null, 26, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 104, 'E150', null, 41, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 105, 'VS Commodore', null, 56, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 106, 'Legacy', null, 23, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 107, 'F430', null, 33, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 108, 'Charger', null, 39, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 109, 'TrailBlazer', null, 18, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 110, 'Golf', null, 59, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 111, 'Durango', null, 33, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 112, 'Rendezvous', null, 68, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 113, 'MX-5', null, 2, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 114, '960', null, 34, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 115, 'Escape', null, 27, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 116, 'MKX', null, 38, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 117, 'LS', null, 11, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 118, 'Eos', null, 5, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 119, '944', null, 9, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 120, 'Mirage', null, 39, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 121, 'Riviera', null, 62, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 122, 'Town Car', null, 17, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 123, 'G5', null, 16, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 124, 'Clubman', null, 30, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 125, '9000', null, 21, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 126, 'Estate', null, 67, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 127, 'LS', null, 65, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 128, 'L-Series', null, 60, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 129, 'F-Series', null, 40, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 130, 'Ram Van B350', null, 70, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 131, '370Z', null, 34, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 132, 'Windstar', null, 42, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 133, 'Navigator', null, 64, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 134, 'Express 2500', null, 3, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 135, 'Spyder', null, 29, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 136, '1500', null, 50, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 137, 'Passat', null, 13, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 138, 'Crossfire', null, 29, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 139, 'Town & Country', null, 7, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 140, 'E-Class', null, 3, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 141, '3500', null, 35, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 142, 'Elantra', null, 64, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 143, 'Journey', null, 20, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 144, 'Spectra', null, 56, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 145, 'Defender', null, 68, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 146, 'FX', null, 32, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 147, 'RL', null, 34, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 148, 'Versa', null, 8, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 149, 'NSX', null, 52, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 150, 'G', null, 48, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 151, 'Pacifica', null, 53, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 152, 'F150', null, 71, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 153, 'Vanagon', null, 61, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 154, 'Grand Prix', null, 17, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 155, 'Grand Marquis', null, 66, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 156, 'Corolla', null, 25, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 157, 'CR-V', null, 70, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 158, 'ES', null, 69, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 159, 'Elantra', null, 50, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 160, 'Aero 8', null, 21, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 161, 'B-Series', null, 16, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 162, 'Express', null, 44, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 163, 'CR-V', null, 13, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 164, 'rio', null, 65, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 165, 'Pilot', null, 24, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 166, '5 Series', null, 10, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 167, 'Mirage', null, 35, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 168, 'E-Series', null, 9, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 169, 'LS', null, 16, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 170, '3500', null, 11, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 171, 'Dakota Club', null, 34, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 172, 'Discovery', null, 65, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 173, 'S8', null, 51, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 174, 'RX', null, 35, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 175, 'Sable', null, 19, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 176, 'Cobalt', null, 40, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 177, 'Type 2', null, 62, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 178, 'S4', null, 24, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 179, 'Z4', null, 43, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 180, 'Mustang', null, 6, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 181, 'Cutlass Cruiser', null, 13, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 182, 'Silverado 3500', null, 51, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 183, '626', null, 14, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 184, 'Gallardo', null, 26, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 185, '924 S', null, 30, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 186, 'Imperial', null, 62, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 187, 'Z4', null, 57, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 188, 'SLK-Class', null, 19, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 189, 'Scoupe', null, 52, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 190, 'LHS', null, 7, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 191, 'TT', null, 40, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 192, 'LR3', null, 12, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 193, 'Malibu', null, 43, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 194, '612 Scaglietti', null, 53, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 195, 'Taurus', null, 65, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 196, 'Vandura 3500', null, 52, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 197, 'M5', null, 60, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 198, 'Golf III', null, 18, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 199, '500', null, 56, null);
insert into shape (dtype, id, name, color, size, complex_id) values ('simple', 200, 'Grand Cherokee', null, 17, null);
